### ISSUE TITLE
Feature Request: Add option to assign edit mode layouts into talent loadouts

### ISSUE THREAD

**Issue by cemtaylor** [Lardeck/TalentLoadoutProfiles#10]
This functionality would help when transitioning between PVE -> PVP which often have very different UI requirements.

I'm not sure how feasible this is, but using [C_EditMode.GetLayouts()](https://wowpedia.fandom.com/wiki/API_C_EditMode.GetLayouts) and [C_EditMode.SetActiveLayout](https://wowpedia.fandom.com/wiki/API_C_EditMode.SetActiveLayout) it seems like it would be possible.

**Comment by Lardeck** [comment]
I will look into it!

**Comment by cemtaylor** [comment]
This works great, thanks!
