### ISSUE TITLE
Lua Error When Opening Simc

### ISSUE THREAD

**Issue by wheatbread** [Lardeck/TalentLoadoutProfiles#16]
Hi,
 
I'm getting the following error when I type /simc to open Simulation Craft and copy my loadout to paste to raidbots. 

https://pastebin.com/7TSJbzE2

Of note is that it mentions sub at the top in the errors, but I was outlaw swapping to another outlaw spec, and never swapped to sub when the errors appeared. 

Also of note is that the builds themselves in the errors are outlaw, and some of them don't even exist anymore--I had deleted them previously from both the addon and default dropdowns  (such as the mage tower and dark brew builds).  

These issues may be related to the other issue I opened a ticket for, wherein Blizzard loadouts for diff builds are showing up in the ImprovedTalentLoadouts dropdowns of a diff build.

**Comment by Lardeck** [comment]
The lua error should be fixed with the next version.
