### ISSUE TITLE
Dropdown does not open

### ISSUE THREAD

**Issue by wheatbread** [Lardeck/TalentLoadoutProfiles#18]
Hi, I'm not sure what prompted the change, but I can no longer open the addon dropdown.  Clicking on it does nothing. :(

![image](https://github.com/Lardeck/ImprovedTalentLoadouts/assets/548824/1854a5c7-c41a-4a03-a4d2-e59d6d340ce1)

**Comment by Lardeck** [comment]
Do you get any Lua errors?
