### ISSUE TITLE
Button Switching Issue(Non Macro)

### ISSUE THREAD

**Issue by Leiserbeamz** [Lardeck/TalentLoadoutProfiles#19]
so when using this addon on my rogue i have a constant issue were it will swap my poisons utility button the one that opens up to all your poisons it will swap it with random ability even after a save like just now it changed it for kidney shot if i replace it with the poisons and resave it will be ok for a while but it does this a lot it has since season 1 for me when i started using this addon 
![image](https://github.com/Lardeck/ImprovedTalentLoadouts/assets/130005581/1820c1b7-b33b-4090-9554-23bbc1bcd10d)
this is the utility im talking about that gets changed a lot

**Comment by Lardeck** [comment]
I will look into it. Not sure why it only happens after some time.

**Comment by Leiserbeamz** [comment]
i wish i could provide a little more detail but im unsure whats causing it it also had been a while since it happened but it just happened again turned my saved loadouts poisons utilities into pickpocket again had to go through all like 8 and resave poison in that spot

**Comment by Leiserbeamz** [comment]
this is still happening and its happening quite frequently now multiple times a day wondering if i have to make a macro for my poisons to get around it at this point

**Comment by Lardeck** [comment]
Should be fixed with the latest release. Please let me know if it still happens.

**Comment by Leiserbeamz** [comment]
i thought thats what it sounded like in the changelog will definitely let you know thank you <3
