### ISSUE TITLE
LUA Error When Using/Updating Talents

### ISSUE THREAD

**Issue by Sekenx** [Lardeck/TalentLoadoutProfiles#20]
Everything is working fine, but I noticed that I get an abundance of these errors:

21x ...ns/ImprovedTalentLoadouts/ImprovedTalentLoadouts.lua:522: bad argument #1 to 'sort' (table expected, got nil)
[string "=[C]"]: in function `sort'
[string "@ImprovedTalentLoadouts/ImprovedTalentLoadouts.lua"]:522: in function <...ns/ImprovedTalentLoadouts/ImprovedTalentLoadouts.lua:516>

Locals:
(*temporary) = nil
(*temporary) = <function> defined @ImprovedTalentLoadouts/ImprovedTalentLoadouts.lua:522
(*temporary) = "table expected, got nil"

**Comment by Lardeck** [comment]
Should be fixed in the next version.

**Comment by Sekenx** [comment]
Thanks man
