### ISSUE TITLE
Rename lacks pre-filled text

### ISSUE THREAD

**Issue by Elitesparkle** [Lardeck/TalentLoadoutProfiles#4]
When renaming a Category or Loadout, even if we only want to change a single letter, we have to write the whole string because the text field is empty, not pre-filled with the previous name.

**Comment by Lardeck** [comment]
Ok, will add it with the next update.

**Comment by Lardeck** [comment]
[Preset old name when renaming loadouts or categories](https://github.com/Lardeck/ImprovedTalentLoadouts/commit/a347cf3f283e0792e8c43607e1422f573172dcf1)
